### ISSUE TITLE
[html]事前レンダリング

### ISSUE THREAD

**Issue by amishiro** [amishiro/AmiTemplate-PHP#63]
事前レンダリング
https://www.suzukikenichi.com/blog/using-prerendering-to-speed-up/

jsonでプリフェッチするページのコントロールできるよう仕込んでおいて、使わなければ削除・・・・かな。そこまでやるなら、事前にやることいっぱいあるだろ・・・とおもわなくもない。検討中。

DNSプリフェッチ
https://www.suzukikenichi.com/blog/dns-prefetching/

DNSプリフェッチは、https通信ではできないためAmiTemplageには組み込まない。

**Comment by toshiyuki-ogawa** [comment]
どちらの改善もbrowserのjavascriptのイベントキューで行われると読めますね。documentのロード前後にjavascriptのイベントキューが一杯になっていると、javascriptのレスポンスが悪くなる可能性もありますよね？次の動作を予測しての改善なので、予想が外れた動作をするとそれほどの速度改善は期待できない場合もありますね。
私もよく速度について厳しい要求を出されることがありますが、要求側はこの辺りのことは全く分かっていないことが多いですよね。私の場合、スループットのどこに問題があるかを、資料を用意して説明して情報を共有するところから始めます。その問題の所在が担当部分にあることがわかる場合のみ対応するようにしています。どうしても早くならないものを早くして欲しいと言われる場合は、プログレスバーなどを表示して、対応したりしています。
これとは別にアルゴリズム上の速度改善は惜しみなく行います。

**Comment by amishiro** [comment]
ogawaさんのおっしゃる通りだと思います。
web利用者の現状を考えみるに、事前レンダリングやプリロード関連をやるなら、かなり的を絞ってやらないとなぁ。と考えてます。（利用するにしても、コンバージョンに絡む部分ぐらいかなと。）

また、レスポンシブサイト化をすると、ユーザーによって通信速度の差が発生します。なので、どのような環境でも出来る限り統一した速度をユーザーに感じてもらうため、（まぁ、ある意味ごまかしなんですが、）フェードで切り替わるようにしたり、１秒以上読み込みが止まる場合は、（プログレスバーまでいかないまでも）おもしろウェイティング画像をだして楽しんでもらったり。

最近なんかは、ウェイティング画面にブランドロゴと一言つける。というのが多いですね。

**Comment by amishiro** [comment]
DNSプリフェッチは、https通信ではできないためAmiTemplageには組み込まない。

事前レンダリングは、場合によるのかなぁ。jsonでプリフェッチするページのコントロールできるよう仕込んでおいて、使わなければ削除・・・・かな。検討中。

**Comment by amishiro** [comment]
うーん。クローズすべきか悩む要件。

**Comment by amishiro** [comment]
現状急ぎではないので一旦保留
