### ISSUE TITLE
画像（に限らず）の拡張子が大文字になっている場合のgulp dest処理について

### ISSUE THREAD

**Issue by hane-jp** [amishiro/AmiTemplate-PHP#81]
画像の拡張子が大文字（例えば：JPG　等）の場合

```$ gulp dest```

の処理で省かれてしまうので、destもしくは前処理で大文字を小文字に変換する処理を入れてもらえると嬉しいです

**Comment by amishiro** [comment]
整形ジャンルですね。

１度処理を実行できればのか、もしくは、毎回destする度に必要でしょうか？

----

例：１度処理・・・ ```$gulp img-min``` 画像圧縮用で、public内のイメージ画像を一括で圧縮してpublicへ上書き。

例：毎回の処理・・・```$gulp js-dest```で毎回jsファイルをミニファイして、destフォルダーへ書き出し。_

**Comment by amishiro** [comment]
@hane-jp 

どう？

**Comment by amishiro** [comment]
情報がないので一旦close
