### ISSUE TITLE
タッチPCにおけるhoverの挙動コントロール

### ISSUE THREAD

**Issue by hane-jp** [amishiro/AmiTemplate-PHP#98]
要検証の部分が多々あると思いますが
vaio z canvas（windows10 pro 64bit）のようなタブレットPCでは
解像度：2556*1526px　でありながらタッチデバイスとして判断されるようで、htmlに書かれるクラス名が「***no-touchevents***」ではなく「***touchevents***」になります。
※windows10の機能の「タブレットモード」は使用していません。

その為:hover疑似クラスに書かれたスタイルが適用されず、マウスオーバーでは変化しません。

その他のタッチディスプレイ搭載のノートPCやSurfaceでも同じ事象が起きるか分からないのですが、気になりましたので報告します

---

対応案

- タッチPCでは、PointerEventsを利用するようにする。
（PointerEventsが利用できる場合は、優先的に利用する。※IE、Edge、chrome対応/safari、FF非対応）
　↓
[Can I use](https://caniuse.com/#search=pointerdown)
- 判定にはmodernizrを利用
```
if (Modernizr.pointerevents) {
  // supported
} else {
  // not-supported
}
```
- polyfile使ってもいいかもしれない
[jquery/PEP](https://github.com/jquery/PEP)
```
$("#canvas").on("pointermove", function(event) {
  draw(event);
});
```
- タッチイベントとの比較
https://w3g.jp/blog/touches_events

---

タスク

- PEP（polyfil）を導入して、pointerEventsを各種ブラウザで動くようにする。＆jQueryのeventでつかえるようにする。
↓
NPM：https://www.npmjs.com/package/pepjs
- mouseEvents/touchEvents/pointerEventsの動作表作成
- hoverにベストな組み合わせを検討
- 導入

**Comment by amishiro** [comment]
touch-events.js内の記述に、```mouseover```と```mouseout```を追加

**Comment by amishiro** [comment]
う～んどうしよう。

**Comment by amishiro** [comment]
ここら辺がポイントになりそう。

マウスデバイスかどうかの判定
↓
https://qiita.com/ksk1015/items/5217bc930cb1ccec2b78

**Comment by amishiro** [comment]
@hane-jp

今度お会いした時に、以下のサイト掲載のクリック時の挙動を確認させてください。

https://muumv.com/click-tap/

**Comment by amishiro** [comment]
しっぽを掴んだかもしれない
↓
https://www.slideshare.net/mobile/eijisekiya/dev-surfacepro3

—-

タッチPC
タッチPC用のjavascriptイベントがある
タッチPC内で利用するブラウザによって挙動が違う

**Comment by amishiro** [comment]
これ読み込む
↓
https://w3g.jp/blog/touches_events

**Comment by amishiro** [comment]
残タスク：

サーフェス実機で動作確認後、materへマージ
↓
http://test.gob.jp/sample_issue98/_sample/_pointer-events/

**Comment by amishiro** [comment]
対応完了
↓
https://github.com/amishiro/AmiTemplate-PHP/releases/tag/v2.0.14
